version: '3.8'

services:
  # Aplicación FastAPI
  app:
    build: .
    container_name: sportbot-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:admin@db:3306/sportbot_db
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=sportbot_collection
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - qdrant
    networks:
      - sportbot-network
    restart: unless-stopped

  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: sportbot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sportbot_db
      MYSQL_USER: sportbot_user
      MYSQL_PASSWORD: sportbot_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - sportbot-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Vector database Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: sportbot-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - sportbot-network
    restart: unless-stopped

  # Redis para caché (opcional)
  redis:
    image: redis:7-alpine
    container_name: sportbot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sportbot-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local
  qdrant_data:
    driver: local
  redis_data:
    driver: local

networks:
  sportbot-network:
    driver: bridge
